repos:
-   repo: local
    hooks:
    -   id: pep8
        name: pep8
        entry: flake8 .
        always_run: true
        pass_filenames: false
        language: system
    -   id: pytest
        name: pytest
        entry: pytest
        always_run: true
        pass_filenames: false
        language: system
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml