version: '3.10'


services:
  db:
    image: postgres:12-alpine
    volumes:
      - .:/app
    ports:
      - "5432:5432"
    env_file: .env-deploy
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "7990:8000"
    env_file: .env-deploy
    command: sh /app/entrypoint.sh
    depends_on:
      - db
